<?php

/**
 * @file
 * Views Dependent Filters module file.
 *
 * Provides a Views exposed filter which makes other filters depend on values
 * in yet further filters for their visibility and processing.
 * For example: if the 'node type' filter is set to 'article', show a filter for
 * a field that is only present on articles.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function views_dependent_filters_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the views_dependent_filters module.
    case 'help.page.views_dependent_filters':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows the presence of exposed filters on a view to be
      controlled by values in another exposed filter. Dependent filters are hidden
      when not relevant, and their values are not considered when the exposed form
      is submitted.') . '</p>';
      return $output;

    default:
  }
}

/**
 * After build form processor for the views exposed form.
 */
function views_dependent_filters_exposed_form_after_build($form, FormStateInterface $form_state) {
  // We may have multiple dependency info arrays from more than one copies
  // of the views_dependent_filters_handler_filter_dependent handler.
  if (empty($form_state->get('dependent_exposed_filters'))) {
    return $form;
  }
  foreach ($form_state->get('dependent_exposed_filters') as $dependency_info) {
    $form_dependency_array = [];
    foreach ($dependency_info['controllers'] as $filter_id => $controller_values) {
      if (array_key_exists($filter_id, $dependency_info['identifiers'])) {
        $identifier = $dependency_info['identifiers'][$filter_id];
        $triggering_values = NULL;
        switch ($dependency_info["condition"]) {
          case 'values':
            $triggering_values = [];
            foreach ($controller_values as $controller_value) {
              $triggering_values[$controller_value] = $controller_value;
            }
            break;
        }
        $form_dependency_array = _views_dependent_filters_get_field_dependency($form, $identifier, $triggering_values);
      }
    }

    // Set the dependency on each form element as required.
    foreach ($dependency_info['dependents'] as $dependent_filter_id) {
      $identifier = $dependency_info['identifiers'][$dependent_filter_id];
      $action = $dependency_info["negate"] ? 'invisible' : 'visible';
      // Add a dependency on its own too, to ensure enabled values stay visible
      // when their controllers are unset.
      $own_dependency = _views_dependent_filters_get_field_dependency($form, $identifier);
      $form_dependency_array = array_merge($form_dependency_array, $own_dependency);
      $form[$identifier]['#states'][$action] = $form_dependency_array;
    }
  }
  return $form;
}

/**
 * Returns the dependency array for a given field.
 */
function _views_dependent_filters_get_field_dependency($form, $identifier, $triggering_values = NULL) {
  $field_dependencies = [];

  if (!$form[$identifier]["#processed"]) {
    return $field_dependencies;
  }

  // When no triggering_values are specified, we assume that all values are
  // triggering.
  if ($triggering_values == NULL) {
    $triggering_values = [];
    if (isset($form[$identifier]["#options"])) {
      $triggering_values = $form[$identifier]["#options"];
      if (isset($triggering_values['All'])) {
        unset($triggering_values['All']);
      }
    }
  }

  switch ($form[$identifier]["#type"]) {
    case 'textfield':
      $field_dependencies[] = [':input[name="' . $identifier . '"]' => ['filled' => TRUE]];
      break;

    case 'checkboxes':
      foreach ($triggering_values as $key => $value) {
        $field_dependencies[] = [':input[name="' . $identifier . '[' . $key . ']"]' => ['checked' => TRUE]];
      }
      break;

    case 'radios':
      foreach ($triggering_values as $key => $value) {
        $field_dependencies[] = [':input[name="' . $identifier . '"]' => ['value' => $key]];
      }
      break;

    case 'select':
      if ($form[$identifier]["#multiple"]) {
        // @todo Find solution for core bug, it is using XOR instead of OR.
        // See https://www.drupal.org/project/drupal/issues/1149078
        $or_values = [];
        foreach ($triggering_values as $key => $value) {
          $or_values[] = ['value' => [(string) $key]];
        }
        $field_dependencies[] = [':input[name="' . $identifier . '[]"]' => $or_values];
      }
      else {
        foreach ($triggering_values as $key => $value) {
          $field_dependencies[] = [':input[name="' . $identifier . '"]' => ['value' => $key]];
        }
      }
      break;

    default:
      $warning = t('The selected widget type %widgettype is not supported by Views Dependent Filters.', ['%widgettype' => $form[$identifier]["#type"]]);
      \Drupal::messenger()->addWarning($warning);
      break;
  }
  return $field_dependencies;
}
