<?php

/**
 * @file
 * The redirect domain module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\redirect_domain\Hook\RedirectDomainHooks;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
#[LegacyHook]
function redirect_domain_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service(RedirectDomainHooks::class)->help($route_name, $route_match);
}
