<?php

/**
 * @file
 * Installation file for Scheduler Access Test module.
 */

/**
 * Implements hook_install().
 */
function scheduler_access_test_install() {
  // The function node_access_needs_rebuild() does not exist at install-time
  // when testing via run-tests.sh, hence protect this from failure. Also we
  // cannot call node_access_rebuild() directly as the node type does not exist
  // at this point, either during run-tests.sh or via simpletest.
  // The NodeAccessRebuild service was introduced in core version 11.4.
  if (\Drupal::hasService('\Drupal\node\NodeAccessRebuild')) {
    \Drupal::service('\Drupal\node\NodeAccessRebuild')->setNeedsRebuild();
  }
  elseif (function_exists('node_access_needs_rebuild')) {
    node_access_needs_rebuild(TRUE);
  }
}

/**
 * Implements hook_uninstall().
 */
function scheduler_access_test_uninstall() {
  if (\Drupal::hasService('\Drupal\node\NodeAccessRebuild')) {
    \Drupal::service('\Drupal\node\NodeAccessRebuild')->setNeedsRebuild();
  }
  else {
    node_access_needs_rebuild(TRUE);
  }
}
