<?php

/**
 * @file
 * Contains metatag_custom_tags.module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\metatag_custom_tags\Hook\HelpHooks;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
#[LegacyHook]
function metatag_custom_tags_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service(HelpHooks::class)->help($route_name, $route_match);
}
