name: Config Ignore
type: module
description: Ignore certain configuration during imports and exports
core_version_requirement: ^8.8 || ^9 || ^10 || ^11
package: Config
configure: config_ignore.settings
