<?php

/**
 * @file
 * Core functions for the Token Filter module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\token_filter\Hook\TokenFilterHooks;

/**
 * Implements hook_preprocess_HOOK().
 */
#[LegacyHook]
function token_filter_preprocess_field(array &$variables) {
  \Drupal::service(TokenFilterHooks::class)->preprocessField($variables);
}

/**
 * Implements hook_migration_plugins_alter().
 */
#[LegacyHook]
function token_filter_migration_plugins_alter(array &$migrations) {
  \Drupal::service(TokenFilterHooks::class)->migrationPluginsAlter($migrations);
}
