<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\menu_ui\MenuForm;
use Drupal\Core\Menu\MenuLinkTreeInterface;


/**
 * @file
 * Menu item limit enables the limitation of items per menu.
 */

/**
 * Implements hook_form_alter().
 */
function menu_item_limit_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  switch ($form_id) {
    case 'menu_edit_form':
      // Extend menu_edit_menu with the limit form.
      $form['menu_item_limit'] = menu_item_limit_config_menu($form, $form_state->getBuildInfo()['callback_object']);
      $form['#validate'][] = 'menu_item_limit_config_menu_validate';
      array_unshift($form['actions']['submit']['#submit'], 'menu_item_limit_config_menu_submit');
      break;

    default:
      break;
  }
}

/**
 * Add a form element to configure the item limitation of a menu.
 *
 * @param array $form
 *   The current menu edit form.
 * @param MenuForm
 *   The MenuForm item.
 *
 * @return array
 *   The prefilled form element.
 */
function menu_item_limit_config_menu($form, MenuForm $menu_form) {
  $menu_name = empty($menu_form->getEntity()->id()) ? 'new' : $menu_form->getEntity()->id();
  // Try to get the current limit of the menu.
  $config = \Drupal::service('config.factory')->getEditable('menu_item_limit.settings');
  $limit = empty($config->get($menu_name)) ? 0 : $config->get($menu_name);
  $config_item = array(
    '#type' => 'textfield',
    '#description' => t('Set the amount of items allowed in this menu. Set 0 to allow unlimited items.'),
    '#title' => t('Item Limitation'),
    '#default_value' => $limit,
  );
  return $config_item;
}

/**
 * Validate the user input for the item limitation.
 *
 * @param array $form
 *   The current menu edit form.
 * @param array $form_state
 *   The current state of the menu edit form.
 */
function menu_item_limit_config_menu_validate($form, FormStateInterface &$form_state) {
  // Check if the entered limit is set to a value of 0 or higher.
  $limit = $form_state->getValue('menu_item_limit');
  if ((!is_numeric($limit)) || ($limit < 0)) {
    form_set_error('menu_item_limit', t('The Item Limitation has to be set to 0 or higher.'));
  }
}

/**
 * Set the new value for the item limitation of the menu.
 *
 * @param array $form
 *   The current menu edit form.
 * @param array $form_state
 *   The current state of the menu edit form.
 */
function menu_item_limit_config_menu_submit($form, FormStateInterface &$form_state) {
  // Set the limit for the menu.
  \Drupal::logger('menu_item_limit')->notice('mymodule submit ') ;
  $limit = $form_state->getValue('menu_item_limit');
  $menu_name = $form_state->getValue('id');
  $config = \Drupal::service('config.factory')->getEditable('menu_item_limit.settings');
  $config->set($menu_name, $limit);
  $config->save();

}

/**
 * Implements hook_entity_type_alter().
 */
function menu_item_limit_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['menu_link_content'])) {
    $entity_types['menu_link_content']->addConstraint('MenuItemOverLimit');
  }
}
